[package]
name = "gameboy"
version = "0.1.0"
authors = ["Zakhary Kaplan <zakharykaplan@gmail.com>"]
edition = "2021"
repository = "https://github.com/zakharykaplan/gameboy"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.56"
clap = { version = "3.1.6", features = ["derive"] }
env_logger = "0.9.0"
log = "0.4.16"
minifb = "0.22.0"
remus = { git = "https://github.com/zakharykaplan/remus" }
thiserror = "1.0.30"
