[package]
name = "gameboy"
version = "0.1.0"
authors = ["Zakhary Kaplan <zakharykaplan@gmail.com>"]
edition = "2021"
repository = "https://github.com/zakharykaplan/gameboy"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1.8", features = ["derive"] }
color-eyre = { version = "0.6.1", default-features = false }
env_logger = "0.9.0"
log = "0.4.16"
minifb = "0.22.0"
remus = { git = "https://github.com/zakharykaplan/remus" }
thiserror = "1.0.30"
